version: '3.8'

services:
  web:
    image: yamaha-motos-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yamaha-motos-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
